# Generated by Django 4.2.11 on 2024-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_service_patient_category'),
    ]
    operations = [
        # Suppression des vues existantes
        migrations.RunSQL('DROP VIEW IF EXISTS "uvwServiceExpenditures";'),
        migrations.RunSQL('DROP VIEW IF EXISTS "uvwServiceUtilization";'),
        migrations.RunSQL('DROP VIEW IF EXISTS "uvwItemExpenditures";'),
        migrations.RunSQL('DROP VIEW IF EXISTS "uvwItemUtilization";'),
                  ]