# Generated by Django 4.2.11 on 2024-08-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_service_patient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(db_column='ItemCode', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(db_column='ServCode', max_length=50),
        ),
    ]
